### ISSUE TITLE
Regarding the models

### ISSUE THREAD

**Issue by Nemesis9450** [yousefkotp/Speech-Emotion-Recognition#1]
Is all the models that you have used are of your own (means you created it ) or you have taken it from some where .

Please reply ASAP.

**Comment by yousefkotp** [comment]
Hello @Nemesis9450, could you elaborate what you mean by saying `taken it from somewhere`? If you run the code in this repo you should get the same results/models/weights.

**Comment by Nemesis9450** [comment]
Taken from somewhere means , no one have used that model before in a
project. You are the first one to do testing with that that models.

**Comment by yousefkotp** [comment]
If you read the [README.md](https://github.com/yousefkotp/Speech-Emotion-Recognition/blob/main/README.md) file, you will notice that the architecture of `RezoNet` is built upon [Deep-Net: A Lightweight CNN-Based Speech Emotion Recognition System Using Deep Frequency Features](https://www.mdpi.com/1424-8220/20/18/5212) paper. I urge you to take a look through the repo before raising issues on the repo.

Moreover, you you shouldn't take those models and submit them as your own without citing the source since it is a violation of copyright and academic integrity -if you are student-.
